### ISSUE TITLE
Metadata / Record creation and update [aggregate task]

### ISSUE THREAD

**Issue by phebal** [galterlibrary/InvenioRDM-at-NU#9]
- [x] As a user, I want to be able to upload a resource file. Done via #4 

- [x] As a user, I want to be able to upload or enter metadata without a resource file. Done via #7 
- [x] As a user, I want to be able to upload resource files with my metadata entries. Done via #4 
- [x] As a user, I want to provide and edit metadata for my uploaded files. (Aspect of this is an authorization issue). Editing of unpublished records done in #8 and #239. 

- [x] As a librarian, I want to provide and edit metadata for uploaded files. (This is more likely to be an authorization issue). Done via #250 
- ~~[ ] As a librarian, I want to be able to upload resource files to metadata entries.~~
